sudo: required
dist: trusty
language: r

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
      - r-cran-rmpi
      - libssh2-1-dev

r_binary_packages:
  - covr
  - batchjobs

after_success:
  - Rscript -e 'library(covr);coveralls()'